In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("fifa_processed.csv")

In [3]:
df.head()

,ID,Name,Age,Nationality,Overall,Club,Value,Pos_simp,Weight,Finishing,Acceleration,Dribbling,Stamina,Strength,Vision,Positioning,GKReflexes,Height_cm
0,158023,L. Messi,31,Argentina,94,FC Barcelona,€110.5M,ATT,159.0,95.0,91.0,97.0,72.0,59.0,94.0,94.0,8.0,170.18
1,20801,Cristiano Ronaldo,33,Portugal,94,Juventus,€77M,ATT,183.0,94.0,89.0,88.0,88.0,79.0,82.0,95.0,11.0,187.96
2,190871,Neymar Jr,26,Brazil,92,Paris Saint-Germain,€118.5M,ATT,150.0,87.0,94.0,96.0,81.0,49.0,87.0,89.0,11.0,175.26
3,193080,De Gea,27,Spain,91,Manchester United,€72M,GK,168.0,13.0,57.0,18.0,43.0,64.0,68.0,12.0,94.0,193.04
4,192985,K. De Bruyne,27,Belgium,91,Manchester City,€102M,MID,154.0,82.0,78.0,86.0,90.0,75.0,94.0,87.0,13.0,180.34

In [4]:
def rank_players(pos, country, age, sortby):
    df_smaller = df
    
    if pos != "Any":
        df_smaller = df_smaller.loc[df["Pos_simp"] == pos]
    if country != "Any":
        df_smaller = df_smaller.loc[df["Nationality"] == country]
    if age != "Any":
        if age == "Below 18":
            df_smaller = df_smaller.loc[df["Age"] < 18]
        if age == "18-21":
            df_smaller = df_smaller.loc[(df["Age"] >= 18) & (df["Age"] < 22)]
        if age == "22-26":
            df_smaller = df_smaller.loc[(df["Age"] >= 22) & (df["Age"] < 27)]
        if age == "27-31":
            df_smaller = df_smaller.loc[(df["Age"] >= 27) & (df["Age"] < 32)]
        if age == "Above 31":
            df_smaller = df_smaller.loc[(df["Age"] > 31)]
    
    df_smaller = df_smaller.sort_values(by = [sortby], ascending = False).head(10)
    df_smaller = df_smaller[["Name", "Pos_simp", "Age", "Nationality", sortby]]
    if len(df_smaller) == 0:
        print("Sorry, no players match your criteria")
    else:
        print(df_smaller)

In [9]:
rank_players("ATT", "France", "18-21", "Acceleration")

                    Name Pos_simp  Age Nationality  Acceleration
155           O. Dembélé      ATT   21      France          93.0
589     A. Saint-Maximin      ATT   21      France          92.0
2936          O. Edouard      ATT   20      France          88.0
5407            M. Diaby      ATT   18      France          87.0
9626   A. Claude Maurice      ATT   20      France          87.0
1098         J. Augustin      ATT   21      France          85.0
4263          M. Maolida      ATT   19      France          84.0
11248        D. Osei Yaw      ATT   19      France          82.0
9925             G. Hein      ATT   21      France          82.0
12090         A. Dzabana      ATT   21      France          81.0

In [6]:
def man_mode(formation, age, country):
    
    df_smaller = df
    
    if country != "Any":
        df_smaller = df_smaller.loc[df["Nationality"] == country]
        
    if age != "Any":
        if age == "Below 18":
            df_smaller = df_smaller.loc[df["Age"] < 18]
        if age == "18-21":
            df_smaller = df_smaller.loc[(df["Age"] >= 18) & (df["Age"] < 22)]
        if age == "22-26":
            df_smaller = df_smaler.loc[(df["Age"] >= 22) & (df["Age"] < 27)]
        if age == "27-31":
            df_smaller = df_smaller.loc[(df["Age"] >= 27) & (df["Age"] < 32)]
        if age == "Above 31":
            df_smaller = df_smaller.loc[(df["Age"] > 31)]
            
    
    
    df_gk = df_smaller.loc[df_smaller["Pos_simp"] == "GK"]
    gk_list = df_gk.head(1)["Name"].tolist()
    
    df_def = df_smaller.loc[df_smaller["Pos_simp"] == "DEF"]
    n_def = int(formation.split("-")[0])
    def_list = df_def.head(n_def)["Name"].tolist()
    
    df_mid = df_smaller.loc[df_smaller["Pos_simp"] == "MID"]
    n_mid = int(formation.split("-")[1])
    mid_list = df_mid.head(n_mid)["Name"].tolist()
    
    df_st = df_smaller.loc[df_smaller["Pos_simp"] == "ATT"]
    n_st = int(formation.split("-")[2])
    st_list = df_st.head(n_st)["Name"].tolist()
    
    team_list = gk_list + def_list + mid_list + st_list
    return team_list

In [10]:
man_mode("4-3-3", "Any", "England")

['J. Pickford',
 'K. Walker',
 'J. Stones',
 'H. Maguire',
 'K. Trippier',
 'D. Alli',
 'J. Lingard',
 'J. Henderson',
 'H. Kane',
 'R. Sterling',
 'J. Vardy']